perf(pipe): into standalone
embarq/safe-pipe pull request #51
Opened 2024-02-13 20:49 UTC by rbalet

## Perf
- Pipe into a standalone component

## Docs
- README: add `>= v17.1.0` implementation

Close the following issue: https://github.com/embarq/safe-pipe/issues

2024-02-13 23:57 UTC, embarq requested changes
Please take a look at the notes I made.

2024-02-13 23:57 UTC, embarq commented on package.json
@rbalet could you please revert changes regarding the package version. I'll handle this before publishing the package to npm

2024-02-13 23:57 UTC, embarq commented on package.json
please do the same for `package-lock.json` as well as the `projects/safe-pipe/package.json` and `projects/safe-pipe/package-lock.json`🙏

2024-02-13 23:57 UTC, embarq commented on projects/safe-pipe/src/lib/safe-pipe.pipe.ts
@rbalet could you please revert the changes regarding the format and identation (if it's not too bothersome). Removing unnecessary changes ensures better diff experience.

2024-02-14 13:12 UTC, rbalet commented on package.json
@embarq Done. sorry, I thought it would be welcome.

I would remove the `projects/safe-pipe/package-lock.json` if I were you as this is not used.

(it should use the one from the parent)

2024-02-14 13:28 UTC, rbalet commented on projects/safe-pipe/src/lib/safe-pipe.pipe.ts
@embarq Hey, I would like to, but I 

1. Added `.prettierrc` with what I assume looks the most like the settings you had. that way the next one that wish to make a pull request wont change the code too much ;).
2. Let vsCode format the code that way

Is this ok?

I think it's better like that than having to open notePad++ to be able to edit your file without changes '^^
But I can do that if you really wishes

2024-02-15 02:00 UTC, embarq commented on projects/safe-pipe/src/lib/safe-pipe.pipe.ts
Adding `.prettierrc` is a great idea. 

I don't get the mention of the notePad++ though but ok.

2024-02-15 02:00 UTC, embarq approved these changes

2024-02-15 02:12 UTC, embarq approved these changes

2024-02-15 02:19 UTC, merged

2024-02-15 07:31 UTC, rbalet commented on projects/safe-pipe/src/lib/safe-pipe.pipe.ts
It was about using a text editor that didn't had any auto text formatting ^^ (yes I know, I'm too lazy to find out how to do so in vsCode)

Thx for your time, see you for angular v18